# Generated by Django 4.1.7 on 2023-02-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(verbose_name="내용"),
        ),
    ]
