# Generated by Django 4.1.7 on 2023-02-15 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rent_day", models.DateField(verbose_name="대여일")),
                ("return_day", models.DateField(verbose_name="반납일")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
